### ISSUE TITLE
InfluxDB migration

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/ImpactPatrol#1]
Migration of the existing DB to our architecture. @Didr as discussed, I would need your help for this, if you're good we could agree on a meeting to do it.

Before that though, @CntoDev/ssgt we need access to the `tools` server for the deployment.

a. install InfluxDB OSS on the server
b. configure the retention policy (2 months as a rough estimate should be fine, can be adjusted for storage optimization)
c. configure HTTP/S authentication and authorization policies
d. actually migrate existing data

**Comment by milivojm** [comment]
Do we need existing data?

**Comment by enrico-ghidoni** [comment]
No we don't, as the new instance would be for both stats and server monitoring.

**Comment by Shiny-CNTO** [comment]
Will you do the work Henrik? 
If so reach out to me so we can create your user together.

**Comment by Didr** [comment]
I will assist Henrik in this. Go ahead and get an account Henrik. :)

About the existing data:
The existing data is all the current CNTR-Stats data. We'd like to keep that. But depending on the time required, it might just be easier to go through all the CNTR logs and re-analyze the data through the script. We'll see!

**Comment by enrico-ghidoni** [comment]
May be a good idea to check the free space on the `tools` server and the available resources before risking to clog it up. Storage can be managed through retention policies, for other resources I have no idea how heavy the db is. We'll check!

EDIT: I believe we comfortably sit within the suggested HW requirements (https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing/)

**Comment by enrico-ghidoni** [comment]
From a quick check, the `tools` server has about 17GB of free disk space and 4GB of RAM. Neither the django-roster nor postgresql are running dockerized, and Docker itself is not installed so that would be a requirement if we intend to setup InfluxDB in a container (which would be nice for portability). On this topic, there is an official image for InfluxDB (https://hub.docker.com/_/influxdb/) so it shouldn't be an issue to move our services to Docker.

@Didr ready when you are!

**Comment by milivojm** [comment]
Can't find Docker system requirements for CentOS Linux. From random web posts they say 4GB RAM "might" be enough. 

https://docs.docker.com/engine/install/centos/

**Comment by enrico-ghidoni** [comment]
I couldn't find anything specific either. But since I do not plan on migrating the already deployed Roster (along with its database) we can containerize InfluxDB and proceed with the goal of this repo and at later time ask if a RAM upgrade is possible (as well as some more storage space, which @Shiny-CNTO mentioned shouldn't be an issue) for deployment of what will be the new Roster application and required services.

**Comment by milivojm** [comment]
Ok, let's do it like that.

**Comment by milivojm** [comment]
Could you please document where new DB is, params etc.

**Comment by enrico-ghidoni** [comment]
Yeah it’s #2.
