### ISSUE TITLE
System configuration documentation

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/ImpactPatrol#2]
Add documentation to this repository including

 - configuration of the various services in the VM
 - explanation of the architecture running the db and Grafana
 - configurations for db and Grafana

**Comment by enrico-ghidoni** [comment]
In addition, mention to

 - users and credentials (@milivojm is there any credential-sharing tools already in use that you know of?)
 - retention policies and estimated DB size
 - permissions of Dashboards

**Comment by enrico-ghidoni** [comment]
Last but not least, `Telegraf` agent configuration on the `main server`. @Didr if you send me the config I'll do it, otherwise feel free to do it yourself.

**Comment by enrico-ghidoni** [comment]
Most of the documentation has been written. Only missing steps to configure `Telegraf` agent on the Windows server which @Didr will work on.

**Comment by Didr** [comment]
Added section for Telegraf. All good to close this @enrico-ghidoni?

**Comment by enrico-ghidoni** [comment]
Looks very good indeed, thank you. Closing this.
