### ISSUE TITLE
Configure Discord alerts

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/ImpactPatrol#3]
Setup push notifications from Grafana to a dedicated Discord channel to alert the community about `main server` resources above a certain threshold.

This needs:
 1. Threshold values for resources to monitor
 2. A dedicated Discord channel and its Webhook URL

**Comment by enrico-ghidoni** [comment]
We will monitor the values of the resources we want to setup alerts for to get a baseline value for setting thresholds.

**Comment by enrico-ghidoni** [comment]
Looking at the data we collected in the past month, I'd set up the alerts as follows

 - CPU (overall usage) >= 90% [highest usage during OP time is ~65%]
 - Free RAM < 2GB [average usage during OP time is ~14GB]
 - C: Disk (system + Arma) free space <5% [current free space is 6%]
 - D: Disk (backups + A3Sync repo host) free space <10% [current free space ~79%]

**Comment by milivojm** [comment]
Lower CPU to 80% please. Also, what about page faults per second?

**Comment by JamesTheClarke** [comment]
> Lower CPU to 80% please. Also, what about page faults per second?

Quick question for the technically challenged: what are "page faults", how do they occur in Arma and what's their impact on the server/players?

**Comment by enrico-ghidoni** [comment]
@JamesTheClarke from my understanding of it, a Page Fault occurs when a process asks the O.S. to retrieve some data in central memory (RAM) but the data is not there, so it has to be loaded in memory from the physical disk which is way slower. Thus the process (or sub-process) that requested such data needs to be put on hold while the thing is actually loaded into RAM. No idea how that impacts Arma gameplay though.

I don't know much about Windows memory allocation policy, but I don't understand why with almost half free memory we had so many page faults yesterday ([look here](https://media.discordapp.net/attachments/281495773894410240/825264576899710986/Screenshot_2021-03-27_Telegraf_Influx_Windows_Host_Overview_-_Grafana3.png?width=1290&height=581) for memory usage and [here](https://media.discordapp.net/attachments/281495773894410240/825264835696001046/unknown.png) for page faults).

@milivojm what threshold would you recommend for page faults? And why lowering the CPU usage to 80%?

By the way, the alerts are already set though I'm waiting for someone from staff to give me a Webhook URL to the Discord channel we want the notifications to be sent to.

**Comment by freghar** [comment]
The page fault amount might be due to old Windows version (does it have the SuperFetch service?) combined with how Arma 3 uses pagefile - there's some direct cache access or something going on, because the game keeps blackscreening **without** a pagefile, despite >50% of my RAM being free.

Windows != Linux in terms of memory management

**Comment by enrico-ghidoni** [comment]
> The page fault amount might be due to old Windows version (does it have the SuperFetch service?) combined with how Arma 3 uses pagefile - there's some direct cache access or something going on, because the game keeps blackscreening **without** a pagefile, despite >50% of my RAM being free.
> 
> Windows != Linux in terms of memory management

That's my concern: is it Arma3 or is it the OS not allocating more memory? Because ~15.5GB used is way below the available memory.

**Comment by milivojm** [comment]
OS is conservative with physical memory allocation and often pages me, always prepared for "another process". I wouldn't be to concerned about page faults, it is normal, still, we want to know if it all goes berserk.

**Comment by enrico-ghidoni** [comment]
Well setting them up would be straightforward, so it's no problem to have it. I wouldn't know what threshold would make sense though.

**Comment by enrico-ghidoni** [comment]
Closing as @Didr set up the alerts to Discord #staff channel with webhook provided to myself by @JamesTheClarke
